apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
commonLabels:
  variant: prod
bases:
- ../../base
patches:
- replicas.yaml
- nodeport.yaml
images:
  - name: nginx
    newTag: 1.12.0
