# originally from http://kubernetesbyexample.com/labels/

apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    env: "davy"
    band: monkees
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
