apiVersion: apps/v1
kind: Deployment
metadata:
  name: buxybox-k-deployment
  labels:
    owner: examplecorp
spec:
  selector:
    matchLabels:
      app: busybox 
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        ports: 
        - containerPort: 80
