apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  variant: dev
bases:
- ../../base
patches:
- nodeport.yaml
images:
  - name: nginx
#    newTag: 1.12.0
    newTag: latest 
