apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: charlie-walnuts-deployment-manager
  namespace: walnuts
subjects:
- kind: ServiceAccount
  name: charlie
  namespace: walnuts
roleRef:
  kind: Role
  name: walnuts-deployment-manager
  apiGroup: rbac.authorization.k8s.io
