apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lucy-walnuts-admin
  namespace: walnuts
subjects:
- kind: ServiceAccount
  name: lucy
  namespace: walnuts
roleRef:
  kind: Role
  name: walnuts-admin
  apiGroup: rbac.authorization.k8s.io
