apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linus-walnuts-pod-watcher
  namespace: walnuts
subjects:
- kind: ServiceAccount
  name: linus
  namespace: walnuts
roleRef:
  kind: Role
  name: walnuts-pod-watcher
  apiGroup: rbac.authorization.k8s.io
