apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-02
  labels:
    volname: vol-02
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.30.201.2
    path: "/export/nfs/vol-02"
