apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: walnuts
  name: walnuts-service-manager
rules:
- apiGroups: [""]
  resources: ["service"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
