apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-node-watcher
subjects:
- kind: ServiceAccount
  name: charlie
  namespace: walnuts
- kind: ServiceAccount
  name: lucy
  namespace: walnuts
- kind: ServiceAccount
  name: linus
  namespace: walnuts
roleRef:
  kind: ClusterRole
  name: cluster-node-watcher
  apiGroup: rbac.authorization.k8s.io
