apiVersion: v1
kind: ConfigMap
metadata:
 namespace: metallb
 name: metallb-config
data:
 config: |
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 172.30.201.200-172.30.201.249
