# originally from http://kubernetesbyexample.com/labels/

apiVersion: v1
kind: Pod
metadata:
  name: john
  labels:
    env: "john"
    band: beatles
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
  nodeSelector:
    band: beatles
